### ISSUE TITLE
hi bro ，do u have the cmakelist version, i can not build in win

### ISSUE THREAD

**Issue by jlk1997** [Helliaca/VXCT#2]

**Comment by Helliaca** [comment]
Hi,

I'm afraid I do not. This was never a cmake project.

There are [other cmake-based projects](https://github.com/JoeyDeVries/LearnOpenGL/blob/master/CMakeLists.txt) that use similar dependencies to mine, so you *could* try to adapt their cmake scripts, though it may involve a significant amount of effort.

Sorry about that!

**Comment by jlk1997** [comment]
why i can not include the base headfile like these
![BQNLAZ `F}3U3D WH2~Y{YO](https://user-images.githubusercontent.com/56379549/234145674-97c67175-8306-48a7-8337-782f444b8930.jpg)
i have not changed the enviroment ,just open the sin
